export const ADD_SELECTED_INGREDIENTS = "ADD_SELECTED_INGREDIENTS" as const;
export const REMOVE_SELECTED_INGREDIENTS = "REMOVE_SELECTED_INGREDIENTS" as const;
export const INGREDIENT_MOVE = 'INGREDIENT_MOVE' as const;
