export const WS_CONNECTION_ALL_ORDERS_START: 'WS_CONNECTION_ALL_ORDERS_START' = 'WS_CONNECTION_ALL_ORDERS_START';
export const WS_CONNECTION_ALL_ORDERS_STOP: 'WS_CONNECTION_ALL_ORDERS_STOP' = 'WS_CONNECTION_ALL_ORDERS_STOP';

export const WS_CONNECTION__ALL_ORDERS_SUCCESS: 'WS_CONNECTION__ALL_ORDERS_SUCCESS' = 'WS_CONNECTION__ALL_ORDERS_SUCCESS';
export const WS_CONNECTION__ALL_ORDERS_ERROR: 'WS_CONNECTION__ALL_ORDERS_ERROR' = 'WS_CONNECTION__ALL_ORDERS_ERROR';
export const WS_CONNECTION__ALL_ORDERS_CLOSED: 'WS_CONNECTION__ALL_ORDERS_CLOSED' = 'WS_CONNECTION__ALL_ORDERS_CLOSED';
export const WS_GET_ALL_ORDERS: 'WS_GET_ALL_ORDERS' = 'WS_GET_ALL_ORDERS';


export const WS_CONNECTION_USER_ORDERS_START: 'WS_CONNECTION_USER_ORDERS_START' = 'WS_CONNECTION_USER_ORDERS_START';
export const WS_CONNECTION_USER_ORDERS_STOP: 'WS_CONNECTION_USER_ORDERS_STOP' = 'WS_CONNECTION_USER_ORDERS_STOP';

export const WS_CONNECTION__USER_ORDERS_SUCCESS: 'WS_CONNECTION__USER_ORDERS_SUCCESS' = 'WS_CONNECTION__USER_ORDERS_SUCCESS';
export const WS_CONNECTION__USER_ORDERS_ERROR: 'WS_CONNECTION__USER_ORDERS_ERROR' = 'WS_CONNECTION__USER_ORDERS_ERROR';
export const WS_CONNECTION__USER_ORDERS_CLOSED: 'WS_CONNECTION__USER_ORDERS_CLOSED' = 'WS_CONNECTION__USER_ORDERS_CLOSED';
export const WS_GET_USER_ORDERS: 'WS_GET_USER_ORDERS' = 'WS_GET_USER_ORDERS';
